### ISSUE TITLE
[ALG] Algorithm

### ISSUE THREAD

**Issue by palmarozaliaosztian** [AlgoRythmics-org/algorythmics-node-api#3]
Implement Algorithm related functionalities

- [ ]  Basic Algorithm model
- [ ] Algorithm DTO
- [ ] .....

**Comment by medvenoemi** [comment]
1. id
2. name
3. description
4. type (sort, search...)
5. visualization type (dance, actor, folk dance...)
6. complexity (best and worse average)
7. difficulty
8. implementation type
9. list <learning step>
